services:
  tgbot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: de-tgbot
    restart: unless-stopped
    env_file:
      - .env
    # Start after these services
    depends_on:
      - pg

  pg:
    image: "postgres:17"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: tgbot
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres  # Read from .env
    volumes:
      # external_directory:internal_directory
      # volume for postgresql data
      - "${DEPLOY_DIR:-.}/data/pg/pgdata:/var/lib/postgresql/data/pgdata"
    ports:
      # "external_port:internal_port"
      - "55432:5432"
