"""initial

Revision ID: 84422e9e35c1
Revises: 
Create Date: 2025-04-25 23:37:18.231644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84422e9e35c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_action',
    sa.Column('action_id', sa.UUID(), nullable=False, comment='ID действия'),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True, comment='Timestamp действия'),
    sa.Column('user_id', sa.INTEGER(), nullable=True, comment='ID пользователя'),
    sa.Column('query_id', sa.UUID(), nullable=True, comment='ID запроса'),
    sa.Column('action', sa.TEXT(), nullable=True, comment='Действие'),
    sa.PrimaryKeyConstraint('action_id'),
    schema='public',
    comment='Действия пользователей'
    )
    op.create_index(op.f('ix_public_t_action_timestamp'), 't_action', [sa.literal_column('timestamp DESC')], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_action_user_id'), 't_action', ['user_id'], unique=False, schema='public')
    op.create_table('t_query',
    sa.Column('query_id', sa.UUID(), nullable=False, comment='ID запроса'),
    sa.Column('user_id', sa.INTEGER(), nullable=True, comment='ID пользователя'),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True, comment='Timestamp действия'),
    sa.Column('status', sa.TEXT(), nullable=True, comment='Статус запроса'),
    sa.Column('query_text', sa.TEXT(), nullable=True, comment='Текст запроса'),
    sa.Column('response_text', sa.TEXT(), nullable=True, comment='Текст ответа'),
    sa.Column('input_text_tokens', sa.INTEGER(), nullable=True, comment='Использование токенов, inputTextTokens'),
    sa.Column('completion_tokens', sa.INTEGER(), nullable=True, comment='Использование токенов, completionTokens'),
    sa.Column('total_tokens', sa.INTEGER(), nullable=True, comment='Использование токенов, totalTokens'),
    sa.PrimaryKeyConstraint('query_id'),
    schema='public',
    comment='Запросы'
    )
    op.create_index(op.f('ix_public_t_query_timestamp'), 't_query', [sa.literal_column('timestamp DESC')], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_t_query_timestamp'), table_name='t_query', schema='public')
    op.drop_table('t_query', schema='public')
    op.drop_index(op.f('ix_public_t_action_user_id'), table_name='t_action', schema='public')
    op.drop_index(op.f('ix_public_t_action_timestamp'), table_name='t_action', schema='public')
    op.drop_table('t_action', schema='public')
    # ### end Alembic commands ###
